name: Build README and Site

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        npm install
    - name: Generate snippets.json [using codes folder]
      run: |
        npm run gen-snip-file
    - name: Update README [using snippets.json]
      run: |-
        npm run gen-index
    - name: Update Site [using snippets.json]
      run: |-
        npm run gen-site
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with: 
        commit_message: "Chore: build snippet, index, site"
        commit_user_name: theSoberSobber
        commit_user_email: akshatshrivastava0010@gmail.com
        commit_author: theSoberSobber
